# Generated by Django 3.0.4 on 2020-03-15 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=128)),
                ('check_in', models.CharField(max_length=16)),
                ('check_out', models.CharField(max_length=16)),
                ('special_rates', models.CharField(max_length=32)),
                ('special_rates_code', models.CharField(max_length=16)),
            ],
        ),
    ]
