# Generated by Django 3.0.4 on 2020-03-18 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelm', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='search',
            old_name='location',
            new_name='destination',
        ),
        migrations.AlterField(
            model_name='search',
            name='special_rates',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='search',
            name='special_rates_code',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
