# Generated by Django 3.0.4 on 2020-03-26 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelm', '0002_auto_20200318_0005'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='recipient',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
