# Generated by Django 3.0.4 on 2020-04-02 00:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hotelm', '0006_auto_20200401_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
